### ISSUE TITLE
java.lang.NoSuchMethodError: mockit.internal.startup.AgentLoader.loadAgent()V

### ISSUE THREAD

**Issue by alexec** [jmockit/jmockit1#551]
Please provide the following information:

* Version of JMockit that was used: 

1.29

* Description of the problem:

I get this error after upgrading from 1.21 to 1.29 when using Maven surefire plugin. Any quick thoughts?

* Please avoid reporting a problem that cannot be reproduced by JMockit project members.
  Instead, include enough information (typically, an example test or more, perhaps accompanied by a
  Maven/Gradle build script) so that other developers can verify the problem in their own environments.

* Also, avoid issues that fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code).
  If you would like to contribute to the project in such areas, please submit Pull Requests.

**Comment by alexec** [comment]
Ok. This was cause because there was a mixture of JMockit jar versions.
