### ISSUE TITLE
Mockup is not working with 1.48 version and with jdk 1.8

### ISSUE THREAD

**Issue by jeyaprakash1989** [jmockit/jmockit1#634]
Please provide the following information:

* Version of JMockit that was used: jmockit-1.48.jar

* Description of the problem :

### **Used TestNG version :** testng-7.0.0.jar

**### Code:**

> public class ContentImageFilter {
> public void testContentImage(Properties prop) {
>  try {
>             new MockUp<Result>() {
>                 @Mock
>                 boolean isBadSender() {
>                     return true;
>                 }
>             };
> catch (Error e) {
>         	e.printStackTrace();
> }
> catch (Exception e) {
>         	e.printStackTrace();
> }
> }
> }

I have set the below javaagent at the start of my app-server start script. I have also cross-checked javaagent prop & it presents in the java process. Even though I used javaagent , I got the quoted exception. 

-javaagent:/home/sas/App/tomcat/webapps/lib/jmockit-1.48.jar

> java.lang.NoClassDefFoundError: Could not initialize class ContentImageFilter$1
> Caused by: java.lang.IllegalStateException: JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was used
> at mockit.internal.startup.Startup.verifyInitialization(Startup.java:60)
> at mockit.MockUp.<clinit>(MockUp.java:53)
>

**Comment by rliesenfeld** [comment]
`MockUp` is working fine with JDK 1.8 in JMockit 1.48. The problem in your case is that running a Java app server with the "-javaagent" parameter is not going to be enough, since app servers usually load application classes (`ContentImageFilter` in this case) and third-party libraries (JMockit) with a *custom class loader*, while the Java agent loads JMockit's `Startup` class with the regular class loader. So, when the mockup gets instantiated, you get two different "instances" of JMockit's classes being mixed up, and it doesn't work.

**Comment by jeyaprakash1989** [comment]
So is there any solution to use jmockit in my app ? I can't mock the Result in  my case. 

new MockUp<Result>() {
                @Mock
                boolean isBadSender() {
                    return true;
                }
            };

**Comment by jeyaprakash1989** [comment]
So is there any solution to use jmockit in my app ? I can't mock in my case.

**Comment by rliesenfeld** [comment]
No, you can only use JMockit in the context of a test suite.

**Comment by jeyaprakash1989** [comment]
But previously the same part of code was working fine in my app with jmockit-1.21.jar without setting the javaagent .

No, you can only use JMockit in the context of a test suite. >> Can you demonstrate some example codes for it ?

**Comment by rliesenfeld** [comment]
See any of the sample test suites under https://github.com/jmockit/jmockit1/tree/master/samples
